config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  resources :groups

  resources :rsvps

  resources :events

  resources :welcome

  resources :conversations do
    resources :messages
  end

  resources :users

  get 'index' => 'welcome#index'
  get 'about' => 'welcome#about'
  get 'faq' => 'welcome#faq'
  get 'blog' => 'welcome#blog'
  get 'contact' => 'welcome#contact'
  get 'privacy' => 'welcome#privacy'
  get 'tos' => 'welcome#tos'
  get 'login' => 'welcome#login'
  get 'dashboard-settings' => 'welcome#dashboard-settings'
  get 'dashboard-settings-step-1' => 'welcome#dashboard-settings-step-1'
  get 'events' => 'welcome#events'
  get 'my-groups' => 'welcome#my-groups'
  get 'my-events' => 'welcome#my-events'
  get 'created-events' => 'welcome#created-events'

  root to: 'welcome#index'
  get 'welcome/index'

  devise_for :users
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :involving, -> (user) do
    where("conversations.sender_id =? OR conversations.recipient_id =?",user.id,user.id)
  end

  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id
end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :conversations, :foreign_key => :sender_id

  after_create :create_default_conversation


  private

  # for demo purposes

  def create_default_conversation
    Conversation.create(sender_id: 1, recipient_id: self.id) unless self.id == 1
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @events = Event.all
    @event = Event.new
    respond_with(@events)
  end

  def show
    respond_with(@event)
  end

  def new
    @event = Event.new
    respond_with(@event)
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.save
    respond_with(@event)
  end

  def update
    @event.update(event_params)
    respond_with(@event)
  end

  def destroy
    @event.destroy
    respond_with(@event)
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:user_id, :title, :description, :starts_at, :ends_at)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @groups = Group.all
    respond_with(@groups)
  end

  def show
    respond_with(@group)
  end

  def new
    @group = Group.new
    respond_with(@group)
  end

  def edit
  end

  def create
    @group = Group.new(group_params)
    @group.save
    respond_with(@group)
  end

  def update
    @group.update(group_params)
    respond_with(@group)
  end

  def destroy
    @group.destroy
    respond_with(@group)
  end

  private
    def set_group
      @group = Group.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:name, :group_id, :description, :admin, :members)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!

  def create
    @conversation = Conversation.find(params[:conversation_id])
    @message = @conversation.messages.build(message_params)
    @message.user_id = current_user.id
    @message.save!

    @path = conversation_path(@conversation)
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  before_action :set_rsvp, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @rsvps = Rsvp.all
    respond_with(@rsvps)
  end

  def show
    respond_with(@rsvp)
  end

  def new
    @rsvp = Rsvp.new
    respond_with(@rsvp)
  end

  def edit
  end

  def create
    @rsvp = Rsvp.new(rsvp_params)
    @rsvp.save
    respond_with(@rsvp)
  end

  def update
    @rsvp.update(rsvp_params)
    respond_with(@rsvp)
  end

  def destroy
    @rsvp.destroy
    respond_with(@rsvp)
  end

  private
    def set_rsvp
      @rsvp = Rsvp.find(params[:id])
    end

    def rsvp_params
      params.require(:rsvp).permit(:user_id, :event_id, :guest_count)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
      @users = User.where.not("id = ?",current_user.id).order("created_at DESC")
      @conversations = Conversation.involving(current_user).order("created_at DESC")
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  def self_or_other(message)
    message.user == current_user ? "self" : "other"
  end

  def message_interlocutor(message)
    message.user == message.conversation.sender ? message.conversation.sender : message.conversation.recipient
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def conversation_interlocutor(conversation)
    conversation.recipient == current_user ? conversation.sender : conversation.recipient
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_event_form_modal.html.erb
  <!-- Modal -->
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
              <%= form_for(@event) do |f| %>
                <% if @event.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

                    <ul>
                    <% @event.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>

                <div class="field">
                  <%= f.label :user_id %><br>
                  <%= f.number_field :user_id %>
                </div>
                <div class="field">
                  <%= f.label :title %><br>
                  <%= f.text_field :title %>
                </div>
                <div class="field">
                  <%= f.label :description %><br>
                  <%= f.text_area :description %>
                </div>
                <div class="field">
                  <%= f.label :starts_at %><br>
                  <%= f.datetime_select :starts_at %>
                </div>
                <div class="field">
                  <%= f.label :ends_at %><br>
                  <%= f.datetime_select :ends_at %>
                </div>
                </div>
                <div class="actions modal-footer">
                  <%= f.submit :class=> 'btn btn-success' %>
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
              <% end %>
            </div>
            <!--<div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Save changes</button>-->
          </div>
        </div>
      </div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :starts_at %><br>
    <%= f.text_field :starts_at, :class => 'form-control', :data => {:provide => 'datepicker'} %>
  </div>

  <div class="form-group">
    <%= f.label :ends_at %><br>
    <%= f.text_field :ends_at, :class => 'form-control', :data => {:provide => 'datepicker'} %>
  </div>
  <div class="form-actions text-right">
    <%= f.submit :class => 'btn btn-success green' %>
  </div>
<% end %>

<script>
  (jQuery, function(){
    $('#timepicker').timepicker();
  })
</script>

app/views/events/edit.html.erb
<!--<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>-->



<div class="container">
	<div class="row">
		<div class="col-md-6">
		  <h1>Edit Event</h1>
		  <ul class="breadcrumb">
		    <li><%= link_to 'Events', events_path %></li>
		    <li><%= link_to 'Edit Event', edit_event_path(@event) %></li>
		  </ul>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<%= render 'form' %>

			<!--<%= link_to 'Back', events_path, :class=> 'btn btn-default' %>-->
		</div>
	</div>
</div>

app/views/events/index.html.erb
<!--<div class="row" ng-view>
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <a href="#" class="navbar-brand"><img src="assets/img/logo.png" alt="Railblazers" height="45px" /></a>
      <ul class="nav navbar-nav navbar-left">
        <li><a href="my-groups.html">Groups</a></li>
        <li class="active"><a href="events.html">Events</a></li>
      </ul>
    </div>
    <div class="nav navbar-nav navbar-right">
      <span class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true" id="dropdownMenu1">
            <img src="http://placehold.it/35x35" alt="avatar" class="img-circle" />
            <span class="caret"></span>
          </a>
          
        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
          <li role="presentation"><a role="menuitem" tabindex="-1" href="dashboard-settings.html">Settings</a></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="dashboard-subscription.html">Subscription</a></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="my-events.html">My Events</a></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="my-groups.html">My Groups</a></li>
        </ul>
      </span>
      <button class="btn btn-default">Sign Out</button>

    </div>
  </div>
</nav>-->


  <!-- Main div -->
  <div class="col-md-12 content-background">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1>Events</h1>
          <ul class="breadcrumb">
            <li><%= link_to 'Events', events_path %></li>
          </ul>
        </div>
        <div class="col-md-6 text-right">
          <div class="clear-space"></div>
          <!--<button class="btn btn-success green" ng-controller="CreateEventModalController" ng-click="openCreateEvent()">
            Create New Event <i class="glyphicon glyphicon-plus"></i> 
          </button>-->
          <!--<%= link_to "<button class='btn btn-success green'><i class='glyphicon glyphicon-plus'></i> Create a New Event</button>".html_safe, new_event_path %>-->
          <button type="button" class="btn btn-success green" data-toggle="modal" data-target="#myModal">
            <i class='glyphicon glyphicon-plus'></i> Create a New Event
          </button>
        </div>
      </div>
      
      <!-- First form -->
      <% @events.each do |event| %>
        <div class="row">
          <div class="col-md-2">
            <img src="http://placehold.it/150x150" alt="placeholder" />
            <h4 class="text-center">
              <!--<a href ng-controller="EditEventModalController" ng-click="openEditEvent(event)"><i class="glyphicon glyphicon-pencil"></i></a>
              <a href ng-controller="CancelEventModalController" ng-click="openCancelEventModal(event)"><i class="glyphicon glyphicon-trash"></i></a>
              -->
              <!--<a href data-toggle="modal" data-target="#eventModal" data="event">
                <i class="glyphicon glyphicon-pencil"></i>
              </a>-->
              <!--<%= link_to '<i class="glyphicon glyphicon-pencil"></i>'.html_safe, :data => {:toggle => 'modal', :target => '#eventModal'} %>-->
              <%= link_to '<i class="glyphicon glyphicon-pencil"></i>'.html_safe, edit_event_path(event) %>
              <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, event, method: :delete, data: { confirm: 'Are you sure?' } %>
            </h4>
          </div>
          <div class="col-md-10">
            <h2 class="custom-heading"><%= link_to event.title, event %></h2>
            <p><%= event.description %></p>
            <p>
              <em>
                <%= event.starts_at.strftime("%A, %B %d, %Y") %><br />
                <%= event.starts_at.strftime(" %I:%M %p") %> - <%= event.ends_at.strftime(" %I:%M %p") %><br />
                <a popover-placement="right" popover="Sample text<br />Sample text" popover-title="Members Going" href> Members Going</a>
              </em>
            </p>
          </div>
        </div>
        <hr />
        <div class="clear-space"></div>
      <% end %>

      <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">

         <!--<%= link_to "<button class='btn btn-success green btn-block text-center'><i class='glyphicon glyphicon-plus'></i> Create a New Event</button>".html_safe, new_event_path %>-->

         <button type="button" class="btn btn-success green btn-block text-center" data-toggle="modal" data-target="#myModal">
            <i class='glyphicon glyphicon-plus'></i> Create a New Event
          </button>


          <!--<button class="btn btn-success green btn-block text-center" ng-controller="CreateEventModalController" ng-click="openCreateEvent()">
            <i class="glyphicon glyphicon-plus"></i> Create a New Event
          </button>-->
        </div>
        <div class="col-md-3"></div>
      </div>
      <div class="clear-space"></div>

       <!-- Modal -->
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
              <%= form_for(@event) do |f| %>
                <% if @event.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

                    <ul>
                    <% @event.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>

                <div class="field">
                  <%= f.label :user_id %><br>
                  <%= f.number_field :user_id %>
                </div>
                <div class="field">
                  <%= f.label :title %><br>
                  <%= f.text_field :title %>
                </div>
                <div class="field">
                  <%= f.label :description %><br>
                  <%= f.text_area :description %>
                </div>
                <div class="field">
                  <%= f.label :starts_at %><br>
                  <%= f.datetime_select :starts_at %>
                </div>
                <div class="field">
                  <%= f.label :ends_at %><br>
                  <%= f.datetime_select :ends_at %>
                </div>
                </div>
                <div class="actions modal-footer">
                  <%= f.submit :class=> 'btn btn-success' %>
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
              <% end %>
            </div>

          </div>
        </div>
      </div>

      <!-- Edit Modal -->
      <div class="modal fade" id="eventModal" tabindex="-1" role="dialog" aria-labelledby="eventModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="eventModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
              <%= form_for(@event) do |f| %>
                <% if @event.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

                    <ul>
                    <% @event.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>

                <div class="field">
                  <%= f.label :user_id %><br>
                  <%= f.number_field :user_id %>
                </div>
                <div class="field">
                  <%= f.label :title %><br>
                  <%= f.text_field :title %>
                </div>
                <div class="field">
                  <%= f.label :description %><br>
                  <%= f.text_area :description %>
                </div>
                <div class="field">
                  <%= f.label :starts_at %><br>
                  <%= f.datetime_select :starts_at %>
                </div>
                <div class="field">
                  <%= f.label :ends_at %><br>
                  <%= f.datetime_select :ends_at %>
                </div>
                </div>
                <div class="actions modal-footer">
                  <%= f.submit :class=> 'btn btn-success' %>
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
              <% end %>
            </div>
            <!--<div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Save changes</button>-->
          </div>
        </div>
      </div>

  
    
    </div><!--container-->
  </div>

<!--</div>-->





<!--<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Description</th>
      <th>Starts at</th>
      <th>Ends at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.user_id %></td>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.starts_at %></td>
        <td><%= event.ends_at %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>-->

app/views/events/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">
		  <h1>New Event</h1>
		  <ul class="breadcrumb">
		    <li><%= link_to 'Events', events_path %></li>
		    <li><%= link_to 'New Event', new_event_path %></li>
		  </ul>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<%= render 'form' %>

			<!--<%= link_to 'Back', events_path, :class=> 'btn btn-default' %>-->
		</div>
	</div>
</div>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-12 content-background">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1><%= @event.title %></h1>
        <ul class="breadcrumb">
          <li><%= link_to 'Events', events_path %></li>
          <li> <%= link_to @event.title, @event %></li>
        </ul>
      </div>

      <div role="tabpanel">

        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" class="active"><a href="#overview" aria-controls="overview" role="tab" data-toggle="tab">Overview</a></li>
          <li role="presentation"><a href="#chat" aria-controls="chat" role="tab" data-toggle="tab">Chat <span class="badge badge-alert">4</span></a></li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="overview">
            <div class="clear-space"></div>
              <div class="row">
                <div class="col-md-2">
                  <img src="http://placehold.it/150x150" alt="placeholder" />
                  <h4 class="text-center">
                    <%= link_to '<i class="glyphicon glyphicon-pencil"></i>'.html_safe, edit_event_path(@event) %>
                    <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, @event, method: :delete, data: { confirm: 'Are you sure?' } %>
                  </h4>
                </div>
                <div class="col-md-10">
                  <h2 class="custom-heading"><%= @event.title %></h2>
                  <p><%= @event.description %></p>
                  <p>
                    <em>
                      <%= @event.starts_at.strftime("%A, %B %d, %Y") %><br />
                      <%= @event.starts_at.strftime(" %I:%M %p") %> - <%= @event.ends_at.strftime(" %I:%M %p") %><br />
                      <!--<a popover-placement="right" popover="Sample text<br />Sample text" popover-title="Members Going" href>{{selectedEvent.rsvps}} Members Going</a>-->
                      <a data-toggle="popover" title="Members Going" data-content="[45] members going">[45] Members Going</a>
                    </em>
                  </p>
                </div>
              </div>
            <!--<p>
              <strong>User:</strong>
              <%= @event.user_id %>
            </p>

            <p>
              <strong>Title:</strong>
              <%= @event.title %>
            </p>

            <p>
              <strong>Description:</strong>
              <%= @event.description %>
            </p>

            <p>
              <strong>Starts at:</strong>
              <%= @event.starts_at %>
            </p>

            <p>
              <strong>Ends at:</strong>
              <%= @event.ends_at %>
            </p>

            <%= link_to 'Edit', edit_event_path(@event) %> |
            <%= link_to 'Back', events_path %>-->

          </div>
          <div role="tabpanel" class="tab-pane" id="chat">...</div>

        </div>
        <div class="clear-space"></div>

      </div>
    </div>
  </div>
</div>

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br>
    <%= f.number_field :group_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :admin %><br>
    <%= f.text_field :admin %>
  </div>
  <div class="field">
    <%= f.label :members %><br>
    <%= f.text_field :members %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Group</th>
      <th>Description</th>
      <th>Admin</th>
      <th>Members</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.group_id %></td>
        <td><%= group.description %></td>
        <td><%= group.admin %></td>
        <td><%= group.members %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Group:</strong>
  <%= @group.group_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @group.description %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @group.admin %>
</p>

<p>
  <strong>Members:</strong>
  <%= @group.members %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/rsvps/edit.html.erb
<h1>Editing rsvp</h1>

<%= render 'form' %>

<%= link_to 'Show', @rsvp %> |
<%= link_to 'Back', rsvps_path %>

app/views/rsvps/index.html.erb
<h1>Listing rsvps</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Event</th>
      <th>Guest count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rsvps.each do |rsvp| %>
      <tr>
        <td><%= rsvp.user_id %></td>
        <td><%= rsvp.event_id %></td>
        <td><%= rsvp.guest_count %></td>
        <td><%= link_to 'Show', rsvp %></td>
        <td><%= link_to 'Edit', edit_rsvp_path(rsvp) %></td>
        <td><%= link_to 'Destroy', rsvp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rsvp', new_rsvp_path %>

app/views/rsvps/new.html.erb
<h1>New rsvp</h1>

<%= render 'form' %>

<%= link_to 'Back', rsvps_path %>

app/views/rsvps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @rsvp.user_id %>
</p>

<p>
  <strong>Event:</strong>
  <%= @rsvp.event_id %>
</p>

<p>
  <strong>Guest count:</strong>
  <%= @rsvp.guest_count %>
</p>

<%= link_to 'Edit', edit_rsvp_path(@rsvp) %> |
<%= link_to 'Back', rsvps_path %>